# Site settings
title: Coding with Larz
email: 
description: > # this means to ignore newlines until "baseurl:"
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: redcarpet
